/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index'
import { Route as ProtectedUsersNewRouteImport } from './routes/_protected/users/new'
import { Route as ProtectedUsersUserIdIndexRouteImport } from './routes/_protected/users/$userId/index'
import { Route as ProtectedUsersUserIdEditRouteImport } from './routes/_protected/users/$userId/edit'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsersNewRoute = ProtectedUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsersUserIdIndexRoute =
  ProtectedUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedUsersUserIdEditRoute =
  ProtectedUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof ProtectedIndexRoute
  '/users/new': typeof ProtectedUsersNewRoute
  '/users': typeof ProtectedUsersIndexRoute
  '/users/$userId/edit': typeof ProtectedUsersUserIdEditRoute
  '/users/$userId': typeof ProtectedUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof ProtectedIndexRoute
  '/users/new': typeof ProtectedUsersNewRoute
  '/users': typeof ProtectedUsersIndexRoute
  '/users/$userId/edit': typeof ProtectedUsersUserIdEditRoute
  '/users/$userId': typeof ProtectedUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/users/new': typeof ProtectedUsersNewRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
  '/_protected/users/$userId/edit': typeof ProtectedUsersUserIdEditRoute
  '/_protected/users/$userId/': typeof ProtectedUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/logout'
    | '/auth/callback'
    | '/'
    | '/users/new'
    | '/users'
    | '/users/$userId/edit'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/logout'
    | '/auth/callback'
    | '/'
    | '/users/new'
    | '/users'
    | '/users/$userId/edit'
    | '/users/$userId'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/logout'
    | '/auth/callback'
    | '/_protected/'
    | '/_protected/users/new'
    | '/_protected/users/'
    | '/_protected/users/$userId/edit'
    | '/_protected/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/users/new': {
      id: '/_protected/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof ProtectedUsersNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/users/$userId/': {
      id: '/_protected/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof ProtectedUsersUserIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/users/$userId/edit': {
      id: '/_protected/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof ProtectedUsersUserIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedUsersNewRoute: typeof ProtectedUsersNewRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
  ProtectedUsersUserIdEditRoute: typeof ProtectedUsersUserIdEditRoute
  ProtectedUsersUserIdIndexRoute: typeof ProtectedUsersUserIdIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedUsersNewRoute: ProtectedUsersNewRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
  ProtectedUsersUserIdEditRoute: ProtectedUsersUserIdEditRoute,
  ProtectedUsersUserIdIndexRoute: ProtectedUsersUserIdIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
